/**
 * Where the app's own copy of the font packs lives.
 *
 * Generated by `scripts/fetch-fonts.mjs` into `public/fonts`, so Vite copies it
 * to the site root verbatim and it is served from the same origin as the app.
 *
 * Anything rendering the player *inside* the editor points here: a `srcdoc`
 * iframe inherits the editor's Content Security Policy, which allows no
 * third-party stylesheet, so the CDN link the exported package uses would be
 * refused and the preview would silently fall back to system fonts — quietly
 * breaking the one thing the preview exists to promise, that what you see is
 * what the LMS shows.
 */
export const APP_FONTS_HREF = '/fonts/fonts.css'
